services:
    db:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: password
    php:
        build: .
        depends_on:
            - db
        volumes:
            - ./../..:/usr/src/bundle
            - ./../../build/test:/usr/src/build
            - ./../../build/.composer-cache:/root/.composer/cache
